// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: cracker/cracker.proto

package cracker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuCores      int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"` // Kapasitas worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_cracker_cracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cracker_cracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_cracker_cracker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

type TaskChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StartIndex    int64                  `protobuf:"varint,2,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`   // Index awal keyspace
	EndIndex      int64                  `protobuf:"varint,3,opt,name=end_index,json=endIndex,proto3" json:"end_index,omitempty"`         // Index akhir keyspace
	TargetHash    string                 `protobuf:"bytes,4,opt,name=target_hash,json=targetHash,proto3" json:"target_hash,omitempty"`    // Hash yang harus di-crack
	NoMoreWork    bool                   `protobuf:"varint,5,opt,name=no_more_work,json=noMoreWork,proto3" json:"no_more_work,omitempty"` // Signal jika pekerjaan selesai
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskChunk) Reset() {
	*x = TaskChunk{}
	mi := &file_cracker_cracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskChunk) ProtoMessage() {}

func (x *TaskChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cracker_cracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskChunk.ProtoReflect.Descriptor instead.
func (*TaskChunk) Descriptor() ([]byte, []int) {
	return file_cracker_cracker_proto_rawDescGZIP(), []int{1}
}

func (x *TaskChunk) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskChunk) GetStartIndex() int64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *TaskChunk) GetEndIndex() int64 {
	if x != nil {
		return x.EndIndex
	}
	return 0
}

func (x *TaskChunk) GetTargetHash() string {
	if x != nil {
		return x.TargetHash
	}
	return ""
}

func (x *TaskChunk) GetNoMoreWork() bool {
	if x != nil {
		return x.NoMoreWork
	}
	return false
}

type CrackResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	FoundPassword string                 `protobuf:"bytes,3,opt,name=found_password,json=foundPassword,proto3" json:"found_password,omitempty"`
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrackResult) Reset() {
	*x = CrackResult{}
	mi := &file_cracker_cracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrackResult) ProtoMessage() {}

func (x *CrackResult) ProtoReflect() protoreflect.Message {
	mi := &file_cracker_cracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrackResult.ProtoReflect.Descriptor instead.
func (*CrackResult) Descriptor() ([]byte, []int) {
	return file_cracker_cracker_proto_rawDescGZIP(), []int{2}
}

func (x *CrackResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CrackResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrackResult) GetFoundPassword() string {
	if x != nil {
		return x.FoundPassword
	}
	return ""
}

func (x *CrackResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_cracker_cracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_cracker_cracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_cracker_cracker_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

var File_cracker_cracker_proto protoreflect.FileDescriptor

const file_cracker_cracker_proto_rawDesc = "" +
	"\n" +
	"\x15cracker/cracker.proto\x12\acracker\"F\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\"\xa5\x01\n" +
	"\tTaskChunk\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vstart_index\x18\x02 \x01(\x03R\n" +
	"startIndex\x12\x1b\n" +
	"\tend_index\x18\x03 \x01(\x03R\bendIndex\x12\x1f\n" +
	"\vtarget_hash\x18\x04 \x01(\tR\n" +
	"targetHash\x12 \n" +
	"\fno_more_work\x18\x05 \x01(\bR\n" +
	"noMoreWork\"\x84\x01\n" +
	"\vCrackResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12%\n" +
	"\x0efound_password\x18\x03 \x01(\tR\rfoundPassword\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\"!\n" +
	"\x03Ack\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived2x\n" +
	"\x0eCrackerService\x122\n" +
	"\aGetTask\x12\x13.cracker.WorkerInfo\x1a\x12.cracker.TaskChunk\x122\n" +
	"\fReportResult\x12\x14.cracker.CrackResult\x1a\f.cracker.AckB\vZ\t./crackerb\x06proto3"

var (
	file_cracker_cracker_proto_rawDescOnce sync.Once
	file_cracker_cracker_proto_rawDescData []byte
)

func file_cracker_cracker_proto_rawDescGZIP() []byte {
	file_cracker_cracker_proto_rawDescOnce.Do(func() {
		file_cracker_cracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cracker_cracker_proto_rawDesc), len(file_cracker_cracker_proto_rawDesc)))
	})
	return file_cracker_cracker_proto_rawDescData
}

var file_cracker_cracker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cracker_cracker_proto_goTypes = []any{
	(*WorkerInfo)(nil),  // 0: cracker.WorkerInfo
	(*TaskChunk)(nil),   // 1: cracker.TaskChunk
	(*CrackResult)(nil), // 2: cracker.CrackResult
	(*Ack)(nil),         // 3: cracker.Ack
}
var file_cracker_cracker_proto_depIdxs = []int32{
	0, // 0: cracker.CrackerService.GetTask:input_type -> cracker.WorkerInfo
	2, // 1: cracker.CrackerService.ReportResult:input_type -> cracker.CrackResult
	1, // 2: cracker.CrackerService.GetTask:output_type -> cracker.TaskChunk
	3, // 3: cracker.CrackerService.ReportResult:output_type -> cracker.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cracker_cracker_proto_init() }
func file_cracker_cracker_proto_init() {
	if File_cracker_cracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cracker_cracker_proto_rawDesc), len(file_cracker_cracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cracker_cracker_proto_goTypes,
		DependencyIndexes: file_cracker_cracker_proto_depIdxs,
		MessageInfos:      file_cracker_cracker_proto_msgTypes,
	}.Build()
	File_cracker_cracker_proto = out.File
	file_cracker_cracker_proto_goTypes = nil
	file_cracker_cracker_proto_depIdxs = nil
}
