// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: cracker/cracker.proto

package cracker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrackerService_GetTask_FullMethodName      = "/cracker.CrackerService/GetTask"
	CrackerService_ReportResult_FullMethodName = "/cracker.CrackerService/ReportResult"
)

// CrackerServiceClient is the client API for CrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definisi untuk komunikasi Master-Worker
type CrackerServiceClient interface {
	// Worker meminta chunk pekerjaan baru (Work Stealing / Pull-based)
	GetTask(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*TaskChunk, error)
	// Worker melaporkan hasil (Found/Not Found)
	ReportResult(ctx context.Context, in *CrackResult, opts ...grpc.CallOption) (*Ack, error)
}

type crackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrackerServiceClient(cc grpc.ClientConnInterface) CrackerServiceClient {
	return &crackerServiceClient{cc}
}

func (c *crackerServiceClient) GetTask(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*TaskChunk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskChunk)
	err := c.cc.Invoke(ctx, CrackerService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerServiceClient) ReportResult(ctx context.Context, in *CrackResult, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CrackerService_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrackerServiceServer is the server API for CrackerService service.
// All implementations must embed UnimplementedCrackerServiceServer
// for forward compatibility.
//
// Service definisi untuk komunikasi Master-Worker
type CrackerServiceServer interface {
	// Worker meminta chunk pekerjaan baru (Work Stealing / Pull-based)
	GetTask(context.Context, *WorkerInfo) (*TaskChunk, error)
	// Worker melaporkan hasil (Found/Not Found)
	ReportResult(context.Context, *CrackResult) (*Ack, error)
	mustEmbedUnimplementedCrackerServiceServer()
}

// UnimplementedCrackerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrackerServiceServer struct{}

func (UnimplementedCrackerServiceServer) GetTask(context.Context, *WorkerInfo) (*TaskChunk, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedCrackerServiceServer) ReportResult(context.Context, *CrackResult) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedCrackerServiceServer) mustEmbedUnimplementedCrackerServiceServer() {}
func (UnimplementedCrackerServiceServer) testEmbeddedByValue()                        {}

// UnsafeCrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrackerServiceServer will
// result in compilation errors.
type UnsafeCrackerServiceServer interface {
	mustEmbedUnimplementedCrackerServiceServer()
}

func RegisterCrackerServiceServer(s grpc.ServiceRegistrar, srv CrackerServiceServer) {
	// If the following call panics, it indicates UnimplementedCrackerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrackerService_ServiceDesc, srv)
}

func _CrackerService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerServiceServer).GetTask(ctx, req.(*WorkerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerService_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrackResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerServiceServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerService_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerServiceServer).ReportResult(ctx, req.(*CrackResult))
	}
	return interceptor(ctx, in, info, handler)
}

// CrackerService_ServiceDesc is the grpc.ServiceDesc for CrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cracker.CrackerService",
	HandlerType: (*CrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _CrackerService_GetTask_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _CrackerService_ReportResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cracker/cracker.proto",
}
