// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: cracker/cracker.proto

package cracker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CrackerService_RegisterWorker_FullMethodName = "/cracker.CrackerService/RegisterWorker"
	CrackerService_GetTask_FullMethodName        = "/cracker.CrackerService/GetTask"
	CrackerService_ReportProgress_FullMethodName = "/cracker.CrackerService/ReportProgress"
	CrackerService_ReportResult_FullMethodName   = "/cracker.CrackerService/ReportResult"
)

// CrackerServiceClient is the client API for CrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrackerServiceClient interface {
	// Worker mendaftar dan melaporkan kemampuan
	RegisterWorker(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*Ack, error)
	// Worker meminta chunk pekerjaan baru (Work Stealing / Pull-based)
	GetTask(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*TaskChunk, error)
	// Worker melaporkan progres chunk
	ReportProgress(ctx context.Context, in *ProgressUpdate, opts ...grpc.CallOption) (*Ack, error)
	// Worker melaporkan hasil (Found/Not Found)
	ReportResult(ctx context.Context, in *CrackResult, opts ...grpc.CallOption) (*Ack, error)
}

type crackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrackerServiceClient(cc grpc.ClientConnInterface) CrackerServiceClient {
	return &crackerServiceClient{cc}
}

func (c *crackerServiceClient) RegisterWorker(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, CrackerService_RegisterWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerServiceClient) GetTask(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*TaskChunk, error) {
	out := new(TaskChunk)
	err := c.cc.Invoke(ctx, CrackerService_GetTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerServiceClient) ReportProgress(ctx context.Context, in *ProgressUpdate, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, CrackerService_ReportProgress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerServiceClient) ReportResult(ctx context.Context, in *CrackResult, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, CrackerService_ReportResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrackerServiceServer is the server API for CrackerService service.
// All implementations must embed UnimplementedCrackerServiceServer
// for forward compatibility
type CrackerServiceServer interface {
	// Worker mendaftar dan melaporkan kemampuan
	RegisterWorker(context.Context, *WorkerInfo) (*Ack, error)
	// Worker meminta chunk pekerjaan baru (Work Stealing / Pull-based)
	GetTask(context.Context, *WorkerInfo) (*TaskChunk, error)
	// Worker melaporkan progres chunk
	ReportProgress(context.Context, *ProgressUpdate) (*Ack, error)
	// Worker melaporkan hasil (Found/Not Found)
	ReportResult(context.Context, *CrackResult) (*Ack, error)
	mustEmbedUnimplementedCrackerServiceServer()
}

// UnimplementedCrackerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCrackerServiceServer struct {
}

func (UnimplementedCrackerServiceServer) RegisterWorker(context.Context, *WorkerInfo) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedCrackerServiceServer) GetTask(context.Context, *WorkerInfo) (*TaskChunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedCrackerServiceServer) ReportProgress(context.Context, *ProgressUpdate) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedCrackerServiceServer) ReportResult(context.Context, *CrackResult) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedCrackerServiceServer) mustEmbedUnimplementedCrackerServiceServer() {}

// UnsafeCrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrackerServiceServer will
// result in compilation errors.
type UnsafeCrackerServiceServer interface {
	mustEmbedUnimplementedCrackerServiceServer()
}

func RegisterCrackerServiceServer(s grpc.ServiceRegistrar, srv CrackerServiceServer) {
	s.RegisterService(&CrackerService_ServiceDesc, srv)
}

func _CrackerService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerServiceServer).RegisterWorker(ctx, req.(*WorkerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerServiceServer).GetTask(ctx, req.(*WorkerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerService_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerServiceServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerService_ReportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerServiceServer).ReportProgress(ctx, req.(*ProgressUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerService_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrackResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerServiceServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerService_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerServiceServer).ReportResult(ctx, req.(*CrackResult))
	}
	return interceptor(ctx, in, info, handler)
}

// CrackerService_ServiceDesc is the grpc.ServiceDesc for CrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cracker.CrackerService",
	HandlerType: (*CrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _CrackerService_RegisterWorker_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _CrackerService_GetTask_Handler,
		},
		{
			MethodName: "ReportProgress",
			Handler:    _CrackerService_ReportProgress_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _CrackerService_ReportResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cracker/cracker.proto",
}

const (
	CrackerAdmin_AddTask_FullMethodName           = "/cracker.CrackerAdmin/AddTask"
	CrackerAdmin_AddTaskBatch_FullMethodName      = "/cracker.CrackerAdmin/AddTaskBatch"
	CrackerAdmin_ApplyTaskAction_FullMethodName   = "/cracker.CrackerAdmin/ApplyTaskAction"
	CrackerAdmin_GetTask_FullMethodName           = "/cracker.CrackerAdmin/GetTask"
	CrackerAdmin_ListTasks_FullMethodName         = "/cracker.CrackerAdmin/ListTasks"
	CrackerAdmin_SetDispatchPaused_FullMethodName = "/cracker.CrackerAdmin/SetDispatchPaused"
	CrackerAdmin_ListWorkers_FullMethodName       = "/cracker.CrackerAdmin/ListWorkers"
)

// CrackerAdminClient is the client API for CrackerAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrackerAdminClient interface {
	AddTask(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*Task, error)
	AddTaskBatch(ctx context.Context, in *TaskBatchSpec, opts ...grpc.CallOption) (*TaskListResponse, error)
	ApplyTaskAction(ctx context.Context, in *TaskActionRequest, opts ...grpc.CallOption) (*Task, error)
	GetTask(ctx context.Context, in *TaskActionRequest, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error)
	SetDispatchPaused(ctx context.Context, in *DispatchControlRequest, opts ...grpc.CallOption) (*DispatchStatus, error)
	ListWorkers(ctx context.Context, in *WorkerListRequest, opts ...grpc.CallOption) (*WorkerListResponse, error)
}

type crackerAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewCrackerAdminClient(cc grpc.ClientConnInterface) CrackerAdminClient {
	return &crackerAdminClient{cc}
}

func (c *crackerAdminClient) AddTask(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, CrackerAdmin_AddTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerAdminClient) AddTaskBatch(ctx context.Context, in *TaskBatchSpec, opts ...grpc.CallOption) (*TaskListResponse, error) {
	out := new(TaskListResponse)
	err := c.cc.Invoke(ctx, CrackerAdmin_AddTaskBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerAdminClient) ApplyTaskAction(ctx context.Context, in *TaskActionRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, CrackerAdmin_ApplyTaskAction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerAdminClient) GetTask(ctx context.Context, in *TaskActionRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, CrackerAdmin_GetTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerAdminClient) ListTasks(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error) {
	out := new(TaskListResponse)
	err := c.cc.Invoke(ctx, CrackerAdmin_ListTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerAdminClient) SetDispatchPaused(ctx context.Context, in *DispatchControlRequest, opts ...grpc.CallOption) (*DispatchStatus, error) {
	out := new(DispatchStatus)
	err := c.cc.Invoke(ctx, CrackerAdmin_SetDispatchPaused_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crackerAdminClient) ListWorkers(ctx context.Context, in *WorkerListRequest, opts ...grpc.CallOption) (*WorkerListResponse, error) {
	out := new(WorkerListResponse)
	err := c.cc.Invoke(ctx, CrackerAdmin_ListWorkers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrackerAdminServer is the server API for CrackerAdmin service.
// All implementations must embed UnimplementedCrackerAdminServer
// for forward compatibility
type CrackerAdminServer interface {
	AddTask(context.Context, *TaskSpec) (*Task, error)
	AddTaskBatch(context.Context, *TaskBatchSpec) (*TaskListResponse, error)
	ApplyTaskAction(context.Context, *TaskActionRequest) (*Task, error)
	GetTask(context.Context, *TaskActionRequest) (*Task, error)
	ListTasks(context.Context, *TaskListRequest) (*TaskListResponse, error)
	SetDispatchPaused(context.Context, *DispatchControlRequest) (*DispatchStatus, error)
	ListWorkers(context.Context, *WorkerListRequest) (*WorkerListResponse, error)
	mustEmbedUnimplementedCrackerAdminServer()
}

// UnimplementedCrackerAdminServer must be embedded to have forward compatible implementations.
type UnimplementedCrackerAdminServer struct {
}

func (UnimplementedCrackerAdminServer) AddTask(context.Context, *TaskSpec) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedCrackerAdminServer) AddTaskBatch(context.Context, *TaskBatchSpec) (*TaskListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTaskBatch not implemented")
}
func (UnimplementedCrackerAdminServer) ApplyTaskAction(context.Context, *TaskActionRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyTaskAction not implemented")
}
func (UnimplementedCrackerAdminServer) GetTask(context.Context, *TaskActionRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedCrackerAdminServer) ListTasks(context.Context, *TaskListRequest) (*TaskListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedCrackerAdminServer) SetDispatchPaused(context.Context, *DispatchControlRequest) (*DispatchStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDispatchPaused not implemented")
}
func (UnimplementedCrackerAdminServer) ListWorkers(context.Context, *WorkerListRequest) (*WorkerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedCrackerAdminServer) mustEmbedUnimplementedCrackerAdminServer() {}

// UnsafeCrackerAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrackerAdminServer will
// result in compilation errors.
type UnsafeCrackerAdminServer interface {
	mustEmbedUnimplementedCrackerAdminServer()
}

func RegisterCrackerAdminServer(s grpc.ServiceRegistrar, srv CrackerAdminServer) {
	s.RegisterService(&CrackerAdmin_ServiceDesc, srv)
}

func _CrackerAdmin_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerAdminServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerAdmin_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerAdminServer).AddTask(ctx, req.(*TaskSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerAdmin_AddTaskBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskBatchSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerAdminServer).AddTaskBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerAdmin_AddTaskBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerAdminServer).AddTaskBatch(ctx, req.(*TaskBatchSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerAdmin_ApplyTaskAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerAdminServer).ApplyTaskAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerAdmin_ApplyTaskAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerAdminServer).ApplyTaskAction(ctx, req.(*TaskActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerAdmin_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerAdminServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerAdmin_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerAdminServer).GetTask(ctx, req.(*TaskActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerAdmin_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerAdminServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerAdmin_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerAdminServer).ListTasks(ctx, req.(*TaskListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerAdmin_SetDispatchPaused_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerAdminServer).SetDispatchPaused(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerAdmin_SetDispatchPaused_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerAdminServer).SetDispatchPaused(ctx, req.(*DispatchControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrackerAdmin_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerAdminServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerAdmin_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerAdminServer).ListWorkers(ctx, req.(*WorkerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrackerAdmin_ServiceDesc is the grpc.ServiceDesc for CrackerAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrackerAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cracker.CrackerAdmin",
	HandlerType: (*CrackerAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _CrackerAdmin_AddTask_Handler,
		},
		{
			MethodName: "AddTaskBatch",
			Handler:    _CrackerAdmin_AddTaskBatch_Handler,
		},
		{
			MethodName: "ApplyTaskAction",
			Handler:    _CrackerAdmin_ApplyTaskAction_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _CrackerAdmin_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _CrackerAdmin_ListTasks_Handler,
		},
		{
			MethodName: "SetDispatchPaused",
			Handler:    _CrackerAdmin_SetDispatchPaused_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _CrackerAdmin_ListWorkers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cracker/cracker.proto",
}
